apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  secret_key_base: aGlnaGx5c2VjcmV0a2V5
  erlang_cookie: M35Jbzc6TyZleEN6JWJyZ05RZmQsRSx0W0hodHtsNWlnMnZHWCg7WU4xMFROQllyd2NTcXNRLC4xUXdsIVBlSg==
